config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'comments/create'
  get 'comments/destroy'
  root "posts#index"
  devise_for :users, controllers: { registrations: 'users/registrations'}

  resources :posts, only: [:index, :create, :destroy, :edit, :update, :show] do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: :create
  end
  resources :users, only: [:index, :show, :edit, :destroy, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :posts, dependent: :destroy
 has_many :favorites
 has_many :favorite_posts, through: :favorites, source: :post
 has_many :comments

 has_many :active_relationships, class_name:"Relationship", foreign_key: :following_id
 has_many :followings, through: :active_relationships, source: :follower

 has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
 has_many :followers, through: :passive_relationships, source: :following
#  has_many :comment_posts, through: :favorites, source: :post
 validates :username, presence: true
 

 def followed_by?(user)
  passive_relationships.find_by(following_id: user.id).present?
 end


 mount_uploader :image, ImageUploader
 mount_uploader :backimage, ImageUploader

 
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end
  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @post = Post.new
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user= User.find(params[:id])
    @users = user.followers
  end

  def update
    @user = User.find(params[:id])
    if current_user == @user
      flash[:success] = 'ユーザー情報を編集しました'
      render :edit
    else
      flash.now[:danger] = "ユーザー情報の編集に失敗しました"
      render :edit
    end
  end




end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<div class = "userfollows">
<% @users.each do |user| %>
  <hr>
  <p><span>username: </span><%= link_to user.username, user_path(user.id) %></p>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>
</div>

app/views/users/follows.html.erb
<div class = "userfollows">
<% @users.each do |user| %>
  <hr>
  <p><span>name:</span><%= link_to user.username, user_path(user.id) %></p>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>
</div>

app/views/users/index.html.erb
<p class = "userindextitle">USER INDEX</p>
<% @users.each do |user| %>






 <div class = "post">

<%# -----------------------ここから投稿の上部分-------------- %>
            <div class = "postcontent">
                  <div class = "postcontentuser">
                       <div class = "imageandname">
                           <div class = "postuserimage">
                            <%= image_tag user.image.url, :size => '70x70',class: "userimage" if user.image.present?%> </div>
                           <div class = "postusername"> <p><span></span><%=link_to user.username, user_path(user.id),class: "fortextdeconone" %></p> </div>
                      </div>
                      <div class = "dataandfunction">
                      <%# ------------- %>
                      <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>

                   <%# -----------------------%>
                      </div>
                 </div>
            </div>


     </div>

     <% end %>

app/views/users/show.html.erb
<div class = "uswrapper">

<%# -------------------------------------- %>

    <div class = "usimagenamewrapper">
    <%= image_tag @user.backimage.url,class: "userbackimage" if @user.backimage.present?%>

                                <div class = "superfunc">
                                <div class = "superfunction">
                                  <label for="label" class = "fas fa-ellipsis-h fa-2x "></label>
                                 <input type ="checkbox" id = "label">
                                   <div class ="hiddenshow">
                                    <%# ----非表示始まりーーー %>
                                    <% if user_signed_in? && current_user == @user %>
                                   <div class = "functionbox">
                                    <%= link_to "削除", "/users/#{@user.id}",method: :delete, class: "postbtn"%>
                                    <%= link_to "編集", "/users/edit",class: "postbtn"%>
                                    </div>
                                    <%end%>
                                   <%# ーーー非表示終わりーーー  %>               
                               </div>
                               </div>
                               </div>
         <div class = "imagenamebox"> 
            <div class = "usimagebox">
                <div class = "userimageinshow">
              <%= image_tag @user.image.url, :size => '100x100',class: "userimage" if @user.image.present?%>
                </div>
                </div>
            <div class = "usnamebox"><%= @user.username %></div>
        </div>
    
    </div>
 <%# --------------------------------------- %>


  <div class = "intindexbox">

        <div class = "usintwrapper">
        <div class = "fas fa-globe-asia userinttitle">自己紹介</div>

        <div class = "usint"><%= @user.introduce %></div>
        <div class = "fas fa-briefcase uscontent">現在の住まい：<%=@user.region%></div><br><br>
        <div class = "fas fa-birthday-cake uscontent">誕生日：<%=@user.birth%></div><br><br>
        <div class = "fas fa-baby-carriage uscontent">年齢：<%=@user.age%></div><br><br>
        <div class = "fas fa-venus-mars uscontent">性別：<%=@user.gender%></div><br>


    
       
<p><%=link_to "フォロー", follows_user_path(@user.id) %></p>
<p><%=link_to "フォロワー", followers_user_path(@user.id) %></p>
<% if current_user != @user %>
    <% if @user.followed_by?(current_user) %>
        <p><%=link_to "フォロー済み", user_relationships_path(@user.id), method: :delete %></p>
    <% else %>
        <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
    <% end %>
<% end %>
    
        </div>


         <div class = "usindexwrapper">

<%# ------------------------------------------------------- %>

         <% if user_signed_in?%>
             <div class = "postform">
                    <div class = "postformtitle">投稿を作成</div>
                  <%= form_for @post do |f| %>
                  <div class = "textareabox">
                   

                       <div class = "textareaclass">
                           <%= f.text_area :content, placeholder: "#{current_user.username}さん ー 今何してる？", class: "textarea" %>
                        </div>


                  <div class = "postimagebtns">
                     <%= f.submit "投稿" ,class: "textsubmit"%>
                     <%= f.label :image, class: "imagebutton" do%>
                        <div class = "fas fa-image fa-lg"></div>
                         <%= f.file_field :image, class: "hidden"%>
                         <%end%>
                          </div>


                          </div>
                          </div>
                 <% end %>

                 <%else%>

               <div class = "postform">
                    <div class = "postformtitle">投稿を作成するにはログイン、または登録が必要です</div>
                  <%= form_for @post do |f| %>
                  <div class = "textareabox">

                       <div class = "textareaclass">
                           <%= f.text_area :content, placeholder: "ゲストさん ー 今何してる？投稿を作成するにはログイン、または登録が必要です", class: "textarea" %>
                        </div>
                        <%end%>


                          </div>
                          </div>

                   <%end%>
<%# ------------------------------------------------ %>
<% @posts.each do |post| %>

      <div class = "post">

<%# -----------------------ここから投稿の上部分-------------- %>
            <div class = "postcontent">
                  <div class = "postcontentuser">
                       <div class = "imageandname">
                           <div class = "postuserimage">
                     <%= image_tag post.user.image.url, :size => '50x50', class: "insideuserimage" if post.user.image.present?%>
                     </div>
                           <div class = "postusername"> <p><span></span><%=link_to post.user.username, user_path(post.user.id),class: "fortextdeconone" %></p> </div>
                      </div>
                      <div class = "dataandfunction">
                           <div class = "postcontentdata"><%= post.created_at.strftime('%Y/%m/%d %H:%M:%S') %></div>
                              <div class = "superfunction">
                              <%= link_to "", post_path(post.id), class: "fas fa-cog todetail"%>
                               </div>
                      </div>
                 </div>
                 <div class = "postcontentmain">
                     <p><span></span><%=simple_format post.content %></p>
                    
                   
                      <div class = "postcontentimage">
                     <%= image_tag post.image.url, :size => '235x270',class: "postcontentimageinside" if post.image.present?%>
                     </div>

                     
                 </div>
            </div>
<%# -------------------投稿の上部分終了--------------------------
--------------------ここから投稿下部分----------------------- %>

          <div class = "postlikecomment">
          <% if user_signed_in? %>
    <% if post.favorited_by?(current_user) %> <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
        <p><span><i class="fas fa-thumbs-up"></i></span><%=link_to post.favorites.count, post_favorites_path(post.id), method: :delete %></p>
    <% else %>
        <p><span><i class="fas fa-thumbs-up">  </i></span><%=link_to post.favorites.count, post_favorites_path(post.id), method: :post %></p>
    <% end %>
  <% else %>
   <%end%>
    <p><span>お気に入り数: </span><%= post.favorites.count %></p>
      

          </div>

          
      

     </div>

 <% end %>


<%# ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー %>


         </div>

</div>





</div>

app/views/users/verification.html.erb
are you sure?